// Generated by CoffeeScript 1.6.3
(function() {
  var DIRNAME, mathmodels, startmodels, volume;

  DIRNAME = 17.2;

  volume = new MathModel();

  volume.WIDTH = 350;

  volume.HEIGHT = 350;

  volume.initTime = 5000;

  volume.container = document.getElementById("volumecontainer");

  volume.populate();

  volume.mathUp();

  volume.camera.position.set(5, 5, 2);

  volume.cameraControls.target.set(0, 0, 1);

  volume.embed(DIRNAME + "/volume.js", new THREE.MeshNormalMaterial({
    opacity: 1
  }), true);

  mathmodels = [volume];

  window.LoadedMathModels = mathmodels;

  startmodels = function() {
    var model, _i, _len;
    for (_i = 0, _len = mathmodels.length; _i < _len; _i++) {
      model = mathmodels[_i];
      model.go();
    }
    return null;
  };

  $(document).ready(function() {
    startmodels();
    return null;
  });

}).call(this);
