// Generated by CoffeeScript 1.6.3
(function() {
  var DIRNAME, mathmodels, shell, startmodels;

  DIRNAME = 20.1;

  MathModel.statustext = $("#modelstatus");

  shell = new MathModel();

  shell.container = document.getElementById("shellcontainer");

  shell.button = $("#shelllivebutton");

  shell.HEIGHT = 300;

  shell.WIDTH = 700;

  shell.populate();

  shell.camera.position.set(0, -1, 6);

  shell.cameraControls.target.set(0, -1, 0);

  shell.embed(DIRNAME + "/shell.js", new THREE.MeshNormalMaterial(), true);

  shell.addaxes(3, 3, 3);

  mathmodels = [shell];

  window.LoadedMathModels = mathmodels;

  startmodels = function() {
    var model, _i, _len;
    for (_i = 0, _len = mathmodels.length; _i < _len; _i++) {
      model = mathmodels[_i];
      model.go();
    }
    return null;
  };

  $(document).ready(function() {
    startmodels();
    return null;
  });

}).call(this);
