// Generated by CoffeeScript 1.6.3
(function() {
  var cone, ellipsoid, epoid, fcyl, hpoid, htrace, mathmodels, startmodels, taco, vtrace;

  MathModel.statustext = $("#modelstatus");

  cone = new MathModel();

  cone.container = document.getElementById("containercone");

  cone.populate();

  cone.camera.position.set(5, 5, 10);

  cone.embed("6/coneobject.js", new THREE.MeshNormalMaterial(), true);

  fcyl = new MathModel();

  fcyl.container = document.getElementById("containerfreakycylinder");

  fcyl.populate();

  fcyl.camera.position.set(5, 5, 10);

  fcyl.embed("6/freakycylinder.js", new THREE.MeshNormalMaterial(), true);

  ellipsoid = new MathModel();

  ellipsoid.container = document.getElementById("containerellipsoid");

  ellipsoid.populate();

  ellipsoid.camera.position.set(3, 3, 6);

  ellipsoid.embed("6/ellipsoid.js", new THREE.MeshNormalMaterial(), true);

  hpoid = new MathModel();

  hpoid.container = document.getElementById("containerhpoid");

  hpoid.populate();

  hpoid.camera.position.set(15, 15, 30);

  hpoid.embed("6/hpoid.js", new THREE.MeshNormalMaterial(), true);

  epoid = new MathModel();

  epoid.container = document.getElementById("containerepoid");

  epoid.populate();

  epoid.camera.position.set(15, 15, 30);

  epoid.embed("6/epoid.js", new THREE.MeshNormalMaterial(), true);

  taco = new MathModel();

  taco.container = document.getElementById("containertaco");

  taco.populate();

  taco.camera.position.set(-15, 15, 30);

  taco.embed("6/taco.js", new THREE.MeshNormalMaterial(), true);

  vtrace = new MathModel();

  vtrace.container = document.getElementById("containerepoidverticaltrace");

  vtrace.populate();

  vtrace.camera.position.set(15, 15, 30);

  vtrace.camera.lookAt(new THREE.Vector3(0, 2, 0));

  vtrace.cameraControls.target.set(0, 2, 0);

  vtrace.embed("6/epoid.js", new THREE.MeshNormalMaterial(), true);

  vtrace.slicer = new THREE.Mesh(new THREE.CubeGeometry(20, 20, 0.01), new THREE.MeshLambertMaterial({
    color: 0xfe0000,
    ambient: 0x333333,
    opacity: 0.5,
    transparent: true,
    reflectivity: 10
  }));

  vtrace.slicer.position.set(0, 4, 0);

  vtrace.scene.add(vtrace.slicer);

  htrace = new MathModel();

  htrace.container = document.getElementById("containerepoidhorizontaltrace");

  htrace.populate();

  htrace.camera.position.set(15, 15, 30);

  htrace.camera.lookAt(new THREE.Vector3(0, 2, 0));

  htrace.cameraControls.target.set(0, 2, 0);

  htrace.embed("6/epoid.js", new THREE.MeshNormalMaterial(), true);

  htrace.slicer = new THREE.Mesh(new THREE.CubeGeometry(20, 20, 0.01), new THREE.MeshLambertMaterial({
    color: 0xfe0000,
    ambient: 0x333333,
    opacity: 0.5,
    transparent: true,
    reflectivity: 10
  }));

  htrace.slicer.rotation.x = Math.PI / 2.0;

  htrace.slicer.position.set(0, 4, 0);

  htrace.scene.add(htrace.slicer);

  mathmodels = [cone, fcyl, ellipsoid, hpoid, epoid, htrace, vtrace, taco];

  window.LoadedMathModels = mathmodels;

  startmodels = function() {
    var model, _i, _len;
    for (_i = 0, _len = mathmodels.length; _i < _len; _i++) {
      model = mathmodels[_i];
      model.go();
    }
    return null;
  };

  $(document).ready(function() {
    startmodels();
    return null;
  });

}).call(this);
